<div class="col1">
    <h5 style="color: white; font-style: bold; text-align: center; margin-top: 10px;">Events & Updates</h5>
    <marquee behavior="scroll" direction="up" onmouseover="this.stop();" onmouseout="this.start();" height="200px;">
        <p style="font-style: bold; color: yellow; text-align: center;">	DUE TO COVID-19 POSTPONEMENT OF 4TH SOUTH ASIAN SEPAKTAKRAW CHAMPIONSHIP AT DHAKA BANGLADESH FROM 7 TO 12 MARCH 2020.
        23RD SUB- JUNIOR NATIONAL CHAMPIONSHIP IS GOING TO BE HELD AT COMPOSITE SPORTS SCHOOL CHANDRAGI RAMDURG BELGAUM KARNATAKA FROM 20 TO 24 MAY 2020.
        DUE TO COVID-19 POSTPONEMENT OF ASIAN SEPAKTAKRAW YOUTH U-21 CHAMPIONSHIP AT CHINESE TAIPEI FROM 7 TO 12 APRIL 2020.
        INDIAN MEN TEAM WIN BRONZE MEDAL AT 18TH ASIAN GAMES 2018 JAKARTA PALEMBANG..
        22ND SUB-JUNIOR NATIONAL CHAMPIONSHIP AT KADAAPA, ANDHRA PRADESH FROM 11TH TO 15TH JANUARY 2020. RESULTS BOYS TEAM EVENT MANIPUR BIHAR ODISHA TAMILNADU GIRLS TEAM EVENT MANIPUR BIHAR ODISHA A.P. BOYS REGU EVENT ODISHA BIHAR MANIPUR TAMILNADU GIRLS REGU EVENT HARYANA MANIPUR MAHARASHTRA A. P. BOYS DOUBLE EVENT HARYANA MIZORAM DELHI MAHARASHTRA GIRLS DOUBLE EVENT A. P. U. P. DELHI MAHARASHTRA .
        30TH SENIOR NATIONAL CHAMPIONSHIP AT RANCHI, JHARKHAND FROM 29TH DECEMBER 2019 TO 2ND JANUARY 2020. RESULTS MEN TEAM EVENT S. S. B. MANIPUR DELHI TAMILNADU WOMEN TEAM EVENT S. S. B. MANIPUR NAGALAND U. P. MEN REGU EVENT S. S. B. MANIPUR MIZORAM NAGALAND WOMEN REGU EVENT MANIPUR NAGALAND S. S. B. ASSAM MEN DOUBLE EVENT JHARKHAND MIZORAM BIHAR KERALA WOMEN DOUBLE EVENT GOA HARYANA BIHAR RAJASTHAN .
        23RD JUNIOR NATIONAL CHAMPIONSHIP AT HYDERABAD TELANGANA FROM 11TH TO 15TH DECEMBER 2019. BOYS TEAM EVENT DELHI TELANGANA BIHAR A.P. GIRLS TEAM EVENT NAGALAND ODISHA GOA BIHAR BOYS REGU EVENT DELHI MANIPUR A.P. BIHAR GIRLS REGU EVENT MANIPUR NAGALAND ODISHA GOA BOYS DOUBLE EVENTMANIPUR TAMILNADU ODISHA TELANGANA GIRLS DOUBLE EVENT MANIPUR HARYANA TELANGANA DELHI .
        INDIAN MEN WON GOLD MEDAL IN REGU EVENT AT 34TH KING`S CUP WORLD CHAMPIONSHIP BANGKOK, THAILAND FROM 24th AUGUST to 1st September 2019..
        INDIAN MEN WON GOLD MEDAL IN REGU EVENT & WON BRONZE MEDAL IN DOUBLE EVENT, WOMEN WON BRONZE MEDAL IN REGU EVENT AT ASIAN SEPAKTAKRAW CHAMPIONSHIP AT KUNMING, CHINA FROM 8TH TO 15TH JUNE 2019..
        INDIAN MEN TEAM WON BRONZE MEDALS (REGU & QUAD EVENT) IN ISTAF WORLD CUP 2018 CHINA AT HULUN BUIR, CHINA FROM 13th TO 18TH NOVEMBER 2018..</p>
    </marquee>  
    <!-- <img src="https://dummyimage.com/640x360/fff/aaa"> <p></p> -->
    <img src="img/about-person-1.jpeg" style="height:18rem">
    <!-- <img src="img/fit_india_logo-b.png"> -->
    <!-- <h4 style="color: white; margin-top: 20px;" >Affilatations</h4><br> -->
    <!-- <img src="https://dummyimage.com/640x360/fff/aaa"> -->
    <!-- <p style="text-align: center; color: white;">ISTAF</p> -->
    <!-- <img src="https://dummyimage.com/640x360/fff/aaa"> -->
    <!-- <p style="text-align: center; color: white;">ASTAF</p> -->
</div>